# MangaForge Settings Configuration
# This file contains all user-configurable settings for MangaForge

# Download settings
download:
  directory: "./downloads"
  max_chapter_workers: 3      # Parallel chapter downloads
  max_image_workers: 10       # Concurrent image downloads per chapter

# Output settings
output:
  default_format: "cbz"       # images, cbz, pdf
  delete_images_after: true   # Delete images after conversion
  image_quality: 100           # JPEG quality (1-100)

# Provider settings
providers:
  enabled:                    # List of enabled provider IDs
    - mock                     # Mock provider for testing
    - bato                     # Bato.to provider

  rate_limits:                # Seconds between requests per provider
    default: 1.0
    mock: 0.1                  # Mock provider can be fast

# Network settings
network:
  timeout: 30                 # Request timeout in seconds
  retry_attempts: 3           # Retry failed downloads
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# UI settings
ui:
  results_per_page: 10        # Search results per page
  chapters_per_page: 10       # Chapters per page
  theme: "default"            # Rich theme

# Logging settings
logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR
  file: "./logs/mangaforge.log"

# Advanced settings
advanced:
  create_subdirectories: true # Create volume/chapter subdirectories
  preserve_metadata: true     # Keep original filenames when possible
  skip_existing: true         # Skip files that already exist