advanced:
  create_subdirectories: true
  preserve_metadata: true
  skip_existing: true
download:
  directory: ./downloads
  max_chapter_workers: 3
  max_image_workers: 10
logging:
  file: ./logs/mangaforge.log
  level: INFO
network:
  retry_attempts: 3
  timeout: 30
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/91.0.4472.124 Safari/537.36
output:
  default_format: cbz
  delete_images_after: true
  image_quality: 100
providers:
  enabled:
  - mock
  - bato
  - weebcentral
  - mangapark
  - mangabuddy
  rate_limits:
    default: 1.0
    mock: 0.1
ui:
  chapters_per_page: 20
  results_per_page: 30
  theme: default
